name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        fortran-compiler: [gfortran-9, gfortran-10, gfortran-11]
        exclude:
          - os: macos-latest
            fortran-compiler: gfortran-9

    steps:
    - uses: actions/checkout@v4

    - name: Setup Fortran
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: ${{ matrix.fortran-compiler }}

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.20'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

    - name: Run Demo
      run: |
        cd build
        ./src/fortran_template_demo

  windows-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja

    - name: Build and Test
      shell: msys2 {0}
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        ctest --output-on-failure
        ./src/fortran_template_demo.exe

  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Fortran
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: gfortran-11

    - name: Install FORD
      run: |
        python -m pip install --upgrade pip
        pip install ford

    - name: Generate Documentation
      run: |
        if [ -f ford.md ]; then
          ford ford.md
        else
          echo "No FORD documentation configuration found"
        fi

    - name: Upload Documentation
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/